version: '3'

services:
  game_server:
    build: ./
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - /public:/public